name: Предложение
description: Идея новой возможности или улучшения
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Какую задачу это решает
      description: Что сейчас неудобно или невозможно сделать.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Что предлагаете
    validations:
      required: true
