"""
Fetch community-shared PoE2 builds from pobarchives.com and resolve them to
PathOfBuilding XML. The original poe.ninja /poe2/api/builds/{version}/search
endpoint requires server-side auth that we can't easily replicate; pobarchives
mirrors community pob shares (including ones generated by poe.ninja) and
exposes them publicly.

Pipeline per build:
  1. GET pobarchives.com homepage -> scrape /build/<archiveId> hrefs
  2. GET pobarchives.com/build/<archiveId> -> extract the pobb.in/<id> link
  3. GET pobb.in/<id>/raw -> base64-url + zlib-encoded PoB share
  4. Decode -> write XML to out_dir
"""

from __future__ import annotations
import argparse, base64, os, re, sys, time, urllib.request, urllib.error, zlib
from pathlib import Path

UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124 Safari/537.36"


def http_get(url: str, timeout: float = 20.0) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA, "Accept": "*/*"})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return r.read()


def list_archive_ids(limit: int) -> list[str]:
    html = http_get("https://pobarchives.com/").decode("utf-8", "replace")
    ids = sorted(set(re.findall(r"/build/([a-zA-Z0-9_-]+)", html)))
    return ids[:limit]


def archive_to_pobbin_id(archive_id: str) -> str | None:
    html = http_get(f"https://pobarchives.com/build/{archive_id}").decode("utf-8", "replace")
    m = re.search(r"https://pobb\.in/([a-zA-Z0-9_-]+)", html)
    return m.group(1) if m else None


def decode_pob_share(b64url: str) -> str:
    b64 = b64url.replace("-", "+").replace("_", "/")
    b64 += "=" * (-len(b64) % 4)
    return zlib.decompress(base64.b64decode(b64)).decode("utf-8", "replace")


def fetch_xml(pobbin_id: str) -> str:
    body = http_get(f"https://pobb.in/{pobbin_id}/raw").decode("ascii", "replace").strip()
    return decode_pob_share(body)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--count", type=int, default=10, help="how many builds to fetch (default 10)")
    ap.add_argument("--out", default="tools/parity/community_builds",
                    help="output dir for build XMLs")
    ap.add_argument("--delay", type=float, default=0.7,
                    help="seconds between requests to be a polite scraper")
    args = ap.parse_args()

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"[fetch] listing up to {args.count} build IDs from pobarchives.com...")
    archive_ids = list_archive_ids(args.count * 2)  # over-fetch to survive failures
    print(f"[fetch] {len(archive_ids)} candidates")

    saved = 0
    for archive_id in archive_ids:
        if saved >= args.count:
            break
        try:
            time.sleep(args.delay)
            pobbin_id = archive_to_pobbin_id(archive_id)
            if not pobbin_id:
                print(f"  [skip] {archive_id}: no pobb.in link")
                continue
            time.sleep(args.delay)
            xml = fetch_xml(pobbin_id)
            if "<PathOfBuilding2" not in xml:
                print(f"  [skip] {archive_id} -> {pobbin_id}: not PoE2 (got {xml[:60]!r}...)")
                continue
            out_path = out_dir / f"{archive_id}_{pobbin_id}.xml"
            out_path.write_text(xml, encoding="utf-8")
            level = re.search(r'level="(\d+)"', xml)
            cls   = re.search(r'className="([^"]+)"', xml)
            asc   = re.search(r'ascendClassName="([^"]+)"', xml)
            print(f"  [ok]   {archive_id} -> {pobbin_id}  "
                  f"L{level.group(1) if level else '?'} "
                  f"{cls.group(1) if cls else '?'}/"
                  f"{asc.group(1) if asc else '?'}  "
                  f"{out_path}")
            saved += 1
        except urllib.error.HTTPError as e:
            print(f"  [fail] {archive_id}: HTTP {e.code}")
        except Exception as e:
            print(f"  [fail] {archive_id}: {type(e).__name__}: {e}")

    print(f"\n[fetch] {saved} builds saved to {out_dir}/")
    return 0 if saved > 0 else 1


if __name__ == "__main__":
    sys.exit(main())
